services:
  meta-db:
    image: mysql:latest
    container_name: mysql-meta
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_meta
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: meta_db

  data-db:
    image: mysql:latest
    container_name: mysql-data
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_data
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: data_db